### ISSUE TITLE
添加侧栏目录

### ISSUE THREAD

**Issue by timebow** [yijian166/md-toc.js#3]
Hi，我尝试使用了你开发的自动生成目录的脚本，感觉很不错。但目录放在前面，拉动页面的时候，目录就看不到了，不知道你有没有考虑将目录放在侧边？如果能在页面拉动时，目录保持可见，我想效果会更好。

**Comment by yijian166** [comment]
@timebow 之前在过年没看这个，目前可以做到侧边啊，我预留了添加`class` 的接口，这样你就可以定义目录的样式了呀^_^

你可以看下这个[Demo](http://learn.hicc.me/html-css/images-audio-video.html)
